import { CuratedCollectionPreview } from "@/types/collection";

export const curatedCollections: CuratedCollectionPreview[] = [
  {
    id: "casa-organizacao",
    title: "Casa e organização",
    description: "Seleção curada para deixar cada cantinho funcional, bonito e com praticidade no dia a dia.",
    image: "/images/products/luminaria-led.jpg",
    tag: "Curadoria para o lar",
    itemCount: 18,
    priceHighlight: "Faixa R$39 - R$189",
    slug: "casa-organizacao",
  },
  {
    id: "achadinhos-femininos",
    title: "Achadinhos femininos",
    description: "Peças e acessórios escolhidos para quem busca estilo, conforto e ótimo custo-benefício.",
    image: "/images/products/fone-bluetooth.jpg",
    tag: "Seleção feminina",
    itemCount: 24,
    priceHighlight: "Mais vendidos da semana",
    slug: "achadinhos-femininos",
  },
  {
    id: "beleza-autocuidado",
    title: "Beleza e autocuidado",
    description: "Combinações de skincare, beleza e bem-estar para sua rotina ficar ainda mais especial.",
    image: "/images/products/kit-skincare.jpg",
    tag: "Kit especial",
    itemCount: 15,
    priceHighlight: "Combos com desconto",
    slug: "beleza-autocuidado",
  },
  {
    id: "itens-virais",
    title: "Itens virais",
    description: "Os produtos que estão em alta nas redes, agrupados para você descobrir tudo em um só lugar.",
    image: "/images/products/fone-bluetooth.jpg",
    tag: "Em tendência",
    itemCount: 12,
    priceHighlight: "Top trends do momento",
    slug: "itens-virais",
  },
  {
    id: "combo-escritorio",
    title: "Combo escritório",
    description: "Acessórios e utilidades para montar um setup funcional, confortável e produtivo.",
    image: "/images/products/luminaria-led.jpg",
    tag: "Combo inteligente",
    itemCount: 10,
    priceHighlight: "Monte seu setup",
    slug: "combo-escritorio",
  },
  {
    id: "kit-viagem",
    title: "Kit viagem",
    description: "Seleção compacta e útil para organizar malas, manter praticidade e viajar com estilo.",
    image: "/images/products/kit-skincare.jpg",
    tag: "Pronto para viajar",
    itemCount: 14,
    priceHighlight: "Essenciais para levar",
    slug: "kit-viagem",
  },
  {
    id: "ofertas-99",
    title: "Ofertas até R$99",
    description: "Coleções econômicas com produtos úteis e desejados, mantendo preço acessível e curadoria premium.",
    image: "/images/products/fone-bluetooth.jpg",
    tag: "Budget premium",
    itemCount: 20,
    priceHighlight: "Tudo até R$99",
    slug: "ofertas-ate-99",
  },
];

export const collectionsHighlights = [
  "Curadoria premium",
  "Combos exclusivos",
  "Kits temáticos",
  "Seleções por ocasião",
];
