import { SearchCatalogItem } from "@/types/search";

export const searchQuickSuggestions = [
  "Feminino",
  "Casa",
  "Skin Care",
  "Shopee",
  "Shein",
  "TikTok Shop",
  "Combos",
  "Ofertas recentes",
] as const;

export const searchCatalogItems: SearchCatalogItem[] = [
  {
    id: "product-fem-bolsa",
    type: "product",
    title: "Bolsa Tiracolo Minimalista",
    description: "Design sofisticado com acabamento premium para looks versáteis.",
    image: "/images/products/luminaria-led.jpg",
    store: "Shopee",
    category: "Feminino",
    price: "R$ 79,90",
    highlight: "Escolha das clientes",
    ctaLabel: "Ver produto",
    tags: ["feminino", "acessórios", "ofertas recentes", "curadoria"],
    link: "https://shopee.com.br",
  },
  {
    id: "product-skin-kit",
    type: "product",
    title: "Kit Skincare Glow Essentials",
    description: "Rotina completa de autocuidado com foco em hidratação e luminosidade.",
    image: "/images/products/kit-skincare.jpg",
    store: "Shein",
    category: "Skin Care",
    price: "R$ 169,90",
    highlight: "Combo favorito",
    ctaLabel: "Ver produto",
    tags: ["skin care", "combos", "beleza", "coleção glow"],
    link: "https://shein.com.br",
  },
  {
    id: "product-casa-luz",
    type: "product",
    title: "Luminária LED Sunset Decor",
    description: "Iluminação ambiente com efeito sunset para cenários elegantes.",
    image: "/images/products/luminaria-led.jpg",
    store: "TikTok Shop",
    category: "Casa",
    price: "R$ 89,90",
    highlight: "Oferta viral",
    ctaLabel: "Ver produto",
    tags: ["casa", "decoração", "ofertas recentes", "viral"],
    link: "https://tiktok.com",
  },
  {
    id: "product-audio",
    type: "product",
    title: "Fone Bluetooth Premium Bass",
    description: "Áudio envolvente e bateria duradoura para rotina, estudo e treino.",
    image: "/images/products/fone-bluetooth.jpg",
    store: "Shopee",
    category: "Tecnologia",
    price: "R$ 129,90",
    highlight: "Mais clicado",
    ctaLabel: "Ver produto",
    tags: ["tecnologia", "eletrônicos", "shopee", "ofertas recentes"],
    link: "https://shopee.com.br",
  },
  {
    id: "store-shopee",
    type: "store",
    title: "Shopee",
    description: "Ofertas rápidas para compras inteligentes com excelente custo-benefício.",
    category: "Marketplace parceiro",
    ctaLabel: "Explorar loja",
    tags: ["marketplace", "ofertas recentes", "feminino", "casa"],
    link: "/lojas#shopee",
  },
  {
    id: "store-shein",
    type: "store",
    title: "Shein",
    description: "Moda e beleza com forte apelo visual e novidades de alta conversão.",
    category: "Marketplace parceiro",
    ctaLabel: "Explorar loja",
    tags: ["moda", "skin care", "feminino", "combos"],
    link: "/lojas#shein",
  },
  {
    id: "store-tiktok",
    type: "store",
    title: "TikTok Shop",
    description: "Produtos virais e criativos alinhados ao comportamento de descoberta.",
    category: "Marketplace parceiro",
    ctaLabel: "Explorar loja",
    tags: ["viral", "casa", "tecnologia", "ofertas recentes"],
    link: "/lojas#tiktok",
  },
  {
    id: "collection-casa",
    type: "collection",
    title: "Casa e organização",
    description: "Seleção curada para deixar cada ambiente funcional e bonito.",
    image: "/images/products/luminaria-led.jpg",
    itemCount: 18,
    badge: "Curadoria para o lar",
    ctaLabel: "Explorar coleção",
    category: "Coleções",
    tags: ["casa", "coleções", "combos", "organização"],
    link: "/colecoes#casa-organizacao",
  },
  {
    id: "collection-fem",
    type: "collection",
    title: "Achadinhos femininos",
    description: "Peças e acessórios para quem busca estilo e ótimo custo-benefício.",
    image: "/images/products/fone-bluetooth.jpg",
    itemCount: 24,
    badge: "Seleção feminina",
    ctaLabel: "Explorar coleção",
    category: "Coleções",
    tags: ["feminino", "coleções", "moda", "ofertas"],
    link: "/colecoes#achadinhos-femininos",
  },
  {
    id: "collection-skin",
    type: "collection",
    title: "Beleza e autocuidado",
    description: "Combinações de skincare e bem-estar para sua rotina ficar ainda mais especial.",
    image: "/images/products/kit-skincare.jpg",
    itemCount: 15,
    badge: "Kit especial",
    ctaLabel: "Explorar coleção",
    category: "Coleções",
    tags: ["skin care", "coleções", "combos", "autocuidado"],
    link: "/colecoes#beleza-autocuidado",
  },
];